Repository Yunjae53/athletic-performance-record-app-server, pull requests merged in 2022-10, with the labels that each got.

#6 Add: 회원 삭제하기 (비식별화 처리)
  controllers/userController.js
  models/userDao.js
  routes/userRouter.js
  services/userService.js
  utils/maskingFunc.js
Labels: 수정 요청

#12 add: 특정회원 측정기록 조회 & 특정 측정기록 및 데이터 조회
  controllers/recordController.js
  middlewares/auth.js
  models/authDao.js
  models/recordDao.js
  routes/recordRouter.js
  services/recordService.js
Labels: 리뷰 요청

#13 update: 설정 수정(app.js, package.json)
  app.js
  package.json
  server.js
Labels: 리뷰 요청

#15 Add: 특정 회원에 대한 측정 기록과 측정 데이터 생성
  controllers/recordController.js
  db/migrations/20221004123239_create_datas_table.sql
  db/migrations/20221006092057_create_types_limits_table.sql
  db/migrations/20221006092327_insert_types_limits_data.sql
  db/migrations/20221006092631_create_datas_trigger.sql
  db/schema.sql
  models/recordDao.js
  routes/recordRouter.js
  services/recordService.js
Labels: Conflict 해결 요청

#16 test: 측정 기록 삭제 테스트
  tests/user.test.js
Labels: 리뷰 요청

#20 [add] record 조회 unit test
  controllers/recordController.js
  package.json
  routes/index.js
  routes/recordRouter.js
  services/recordService.js
  tests/record.test.js
Labels: 리뷰 요청

#22 Update: 측정 기록 삭제 테스트 - package.json 수정
  package-lock.json
Labels: Conflict 해결 요청

#24 Docs : readme 수정
  README.md
Labels: 리뷰 요청

#7 user_info
  controllers/userController.js
  models/db.config.js
  models/userDao.js
  routes/userRouter.js
  services/userService.js
Labels: Conflict 해결 요청, 리뷰 요청

#25 Update: 에러 문구 수정 & README 수정
  README.md
  middlewares/auth.js
Labels: 리뷰 요청

#33 Update: 키 명칭 변경
  controllers/userController.js
  models/userDao.js
  services/userService.js
Labels: 리뷰 요청
